### ISSUE TITLE
support paired-end reads?

### ISSUE THREAD

**Issue by nick-youngblut** [zjshi/gt-pro#55]
I do not see anything in the docs (`GT_Pro optimize` help docs, the repo README, or [Shi et al., 2023](https://doi.org/10.1016/j.xpro.2022.101964)) on handling paired-end reads. 

How should one handle paired-end reads with `GT_Pro optimize`:

* Just supply all read files (e.g., `GT_Pro optimize read1.fastq read2.fastq`)?
* Just use the forward reads?
* Interleave the forward and reverse reads?

@bsmith89 did you use paired-end reads for genotyping with GT-Pro in order to generate the input for StrainFacts? I don't seen anything in the [StrainFacts README](https://github.com/bsmith89/StrainFacts) about handling paired-end reads. I also can't find info in [Smith et al., 2022](https://doi.org/10.3389/fbinf.2022.867386) about paired-end reads (e.g., whether paired-end were used in the study).

**Comment by nick-youngblut** [comment]
I now see where reverse reads are mentioned in the Maast + GT-Pro protocol:

> In practice, users would genotype forward and reverse reads, if both are available. This can be done by supplying both forward and reverse reads as either two individual input files or a single concatenated file. The command does not need to be modified otherwise.

**Comment by bsmith89** [comment]
Yeah, just to confirm the details, since GT-Pro uses direct kmer matching, the pairing of reads doesn't contain any additional information beyond the deeper sequencing it provides. There is a bit of subtlety with statistical non-independence of the pair, and GT-Pro ignores this. But that effect is probably relatively small and I think it's pretty reasonable to treat it as "just more sequence" to count kmers in.
